"""add date

Revision ID: 70622acfe8cf
Revises: b3153f070180
Create Date: 2024-12-21 17:07:41.961280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70622acfe8cf'
down_revision: Union[str, None] = 'b3153f070180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrows', 'date_borrow',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('borrows', 'date_return',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrows', 'date_return',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('borrows', 'date_borrow',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
